server:
  port: 8482

spring:
  application:
    name: llmhub

llmhub:
  web-client:
    connect-timeout-ms: 3000
    response-timeout-ms: 0
    max-in-memory-size-bytes: 2097152
    max-connections: 500
    pending-acquire-max-count: 1000
    pending-acquire-timeout-ms: 5000
  provider:
    openai:
      endpoint: https://api.openai.com/v1/chat/completions
      api-key: ${OPENAI_API_KEY:}
      param-override:
        model:
          "[*]": GPT-5 mini
    openai2:
      endpoint: https://api.openai.com/v1/chat/completions
      api-key: ${OPENAI_API_KEY2:}
      param-override:
        model:
          "[*]": GPT-5.6 Sol
  default-provider: openai
